# Generated by Django 4.2.25 on 2025-10-25 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('emplacement', models.CharField(max_length=150)),
                ('etat', models.CharField(default='hors ligne', max_length=50)),
                ('derniere_connexion', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(default='fixe', max_length=50)),
            ],
            options={
                'verbose_name': 'Caméra de Surveillance',
                'verbose_name_plural': 'Caméras de Surveillance',
            },
        ),
        migrations.CreateModel(
            name='Capteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('emplacement', models.CharField(max_length=150)),
                ('statut', models.CharField(default='actif', max_length=50)),
                ('derniere_mesure', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capteur',
                'verbose_name_plural': 'Capteurs',
            },
        ),
        migrations.CreateModel(
            name='SiteClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du site')),
                ('adresse', models.TextField(verbose_name='Adresse complète')),
                ('contact_principal', models.CharField(max_length=100, verbose_name='Contact principal')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=50, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Site Client',
                'verbose_name_plural': 'Sites Clients',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('technicien', 'Technicien'), ('client', 'Client')], default='client', max_length=20),
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evenement', models.CharField(max_length=100)),
                ('niveau_urgence', models.CharField(choices=[('critique', 'Critique'), ('eleve', 'Élevé'), ('moyen', 'Moyen'), ('faible', 'Faible')], default='moyen', max_length=50)),
                ('date_detection', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu')], default='en_cours', max_length=50)),
                ('description', models.TextField()),
                ('camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.camerasurveillance')),
                ('capteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.capteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_detection'],
            },
        ),
        migrations.AddField(
            model_name='capteur',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient'),
        ),
        migrations.AddField(
            model_name='camerasurveillance',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient'),
        ),
        migrations.CreateModel(
            name='Alerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name="Message de l'alerte")),
                ('niveau', models.CharField(choices=[('critique', 'Critique'), ('moyen', 'Moyen'), ('info', 'Info')], default='info', max_length=50, verbose_name='Niveau')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('statut', models.CharField(choices=[('envoyee', 'Envoyée'), ('lue', 'Lue'), ('archivee', 'Archivée')], default='envoyee', max_length=50, verbose_name='Statut')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.evenement', verbose_name='Événement')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
