# Generated by Django 4.2.25 on 2025-10-25 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_camerasurveillance_capteur_siteclient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camerasurveillance',
            options={'ordering': ['-derniere_connexion'], 'verbose_name': 'Caméra de Surveillance', 'verbose_name_plural': 'Caméras de Surveillance'},
        ),
        migrations.AlterModelOptions(
            name='capteur',
            options={'ordering': ['-derniere_mesure'], 'verbose_name': 'Capteur', 'verbose_name_plural': 'Capteurs'},
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='derniere_connexion',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière connexion'),
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='emplacement',
            field=models.CharField(max_length=150, verbose_name='Emplacement'),
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='etat',
            field=models.CharField(choices=[('en_ligne', 'En ligne'), ('hors_ligne', 'Hors ligne'), ('maintenance', 'En maintenance')], default='hors_ligne', max_length=50, verbose_name='État'),
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom de la caméra'),
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='camerasurveillance',
            name='type',
            field=models.CharField(choices=[('fixe', 'Fixe'), ('ptz', 'PTZ (Pan-Tilt-Zoom)'), ('thermique', 'Thermique'), ('dome', 'Dôme')], default='fixe', max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='derniere_mesure',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière mesure'),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='emplacement',
            field=models.CharField(max_length=150, verbose_name='Emplacement'),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='statut',
            field=models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('defectueux', 'Défectueux')], default='actif', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='capteur',
            name='type',
            field=models.CharField(choices=[('mouvement', 'Détecteur de Mouvement'), ('fumee', 'Détecteur de Fumée'), ('temperature', 'Capteur de Température'), ('humidite', "Capteur d'Humidité"), ('intrusion', "Détecteur d'Intrusion"), ('gaz', 'Détecteur de Gaz')], max_length=100, verbose_name='Type de capteur'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.camerasurveillance', verbose_name='Caméra'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='capteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.capteur', verbose_name='Capteur'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='date_detection',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de détection'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='niveau_urgence',
            field=models.CharField(choices=[('critique', 'Critique'), ('eleve', 'Élevé'), ('moyen', 'Moyen'), ('faible', 'Faible')], default='moyen', max_length=50, verbose_name="Niveau d'urgence"),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('resolu', 'Résolu')], default='en_cours', max_length=50, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('intrusion', 'Intrusion'), ('incendie', 'Incendie'), ('mouvement', 'Mouvement Suspect'), ('alarme', "Déclenchement d'Alarme"), ('panne', 'Panne Technique')], max_length=100, verbose_name="Type d'événement"),
        ),
        migrations.CreateModel(
            name='RapportSurveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('periode', models.CharField(max_length=100, verbose_name='Période couverte')),
                ('contenu', models.TextField(verbose_name='Contenu du rapport')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Rapport de Surveillance',
                'verbose_name_plural': 'Rapports de Surveillance',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(max_length=100, verbose_name='Équipement')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('technicien', models.CharField(max_length=100, verbose_name='Technicien')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('en_cours', 'En cours'), ('realisee', 'Réalisée'), ('annulee', 'Annulée')], default='planifiee', max_length=50, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.siteclient', verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date_prevue'],
            },
        ),
    ]
