# Generated by Django 4.2.25 on 2025-10-27 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_camerasurveillance_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='cout_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Coût estimé'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='duree_estimee',
            field=models.PositiveIntegerField(default=1, verbose_name='Durée estimée (heures)'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='priorite',
            field=models.CharField(choices=[('faible', 'Faible'), ('moyenne', 'Moyenne'), ('elevee', 'Élevée'), ('critique', 'Critique')], default='moyenne', max_length=50, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type_maintenance',
            field=models.CharField(choices=[('preventive', 'Préventive'), ('curative', 'Curative'), ('predictive', 'Prédictive')], default='preventive', max_length=50, verbose_name='Type de maintenance'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='technicien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Technicien'),
        ),
    ]
