# Generated by Django 4.2.25 on 2025-10-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_maintenance_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportsurveillance',
            name='titre',
            field=models.CharField(default='', max_length=200, verbose_name='Titre du rapport'),
            preserve_default=False,
        ),
    ]
