# Generated by Django 4.2.25 on 2025-10-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rapportsurveillance_titre'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerte',
            name='actions_recommandees',
            field=models.JSONField(blank=True, null=True, verbose_name='Actions recommandées'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='categorie_ia',
            field=models.CharField(blank=True, choices=[('intrusion', 'Intrusion'), ('incendie', 'Incendie'), ('technique', 'Problème Technique'), ('fausse_alerte', 'Fausse Alerte'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Catégorie IA'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='confiance_ia',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Confiance IA'),
        ),
        migrations.AddField(
            model_name='alerte',
            name='explication_ia',
            field=models.TextField(blank=True, null=True, verbose_name='Explication IA'),
        ),
    ]
