# Generated by Django 4.2 on 2025-10-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alerte_actions_recommandees_alerte_categorie_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerasurveillance',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance IA'),
        ),
        migrations.AddField(
            model_name='camerasurveillance',
            name='ai_enabled',
            field=models.BooleanField(default=True, verbose_name='IA activée'),
        ),
        migrations.AddField(
            model_name='camerasurveillance',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées IA'),
        ),
        migrations.AddField(
            model_name='camerasurveillance',
            name='last_ai_analysis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière analyse IA'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='Confiance IA'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='ai_enabled',
            field=models.BooleanField(default=True, verbose_name='IA activée'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, verbose_name='Métadonnées IA'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='last_ai_analysis',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière analyse IA'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valeur maximale attendue'),
        ),
        migrations.AddField(
            model_name='capteur',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Valeur minimale attendue'),
        ),
    ]
